import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { DirectionProvider } from "@/components/ui/direction";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic", "latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", vazirmatn.variable, "font-sans")}
      suppressHydrationWarning
      dir="rtl"
    >
      <body className="dark:selection:bg-neutral-700 selection:bg-blue-700 selection:text-white ">
        <DirectionProvider direction="rtl">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
